// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: auth_server.proto

package serverpb

import (
	modelpb "edu.centraluniversity/internal/modelpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_server_proto protoreflect.FileDescriptor

const file_auth_server_proto_rawDesc = "" +
	"\n" +
	"\x11auth_server.proto\x12\x04main\x1a\vmodel.proto2\x89\x02\n" +
	"\x04Auth\x12\"\n" +
	"\x06SignUp\x12\n" +
	".main.User\x1a\f.main.Result\x12-\n" +
	"\x06SignIn\x12\x15.main.UserCredentials\x1a\f.main.Result\x12+\n" +
	"\vSignInByJwt\x12\x0e.main.JwtToken\x1a\f.main.Result\x12&\n" +
	"\n" +
	"UpdateUser\x12\n" +
	".main.User\x1a\f.main.Result\x12,\n" +
	"\n" +
	"DeleteUser\x12\f.main.UserId\x1a\x10.main.Successful\x12+\n" +
	"\vGetUserInfo\x12\f.main.UserId\x1a\x0e.main.UserInfoB@\n" +
	"\x15edu.centraluniversityZ'edu.centraluniversity/internal/serverpbb\x06proto3"

var file_auth_server_proto_goTypes = []any{
	(*modelpb.User)(nil),            // 0: main.User
	(*modelpb.UserCredentials)(nil), // 1: main.UserCredentials
	(*modelpb.JwtToken)(nil),        // 2: main.JwtToken
	(*modelpb.UserId)(nil),          // 3: main.UserId
	(*modelpb.Result)(nil),          // 4: main.Result
	(*modelpb.Successful)(nil),      // 5: main.Successful
	(*modelpb.UserInfo)(nil),        // 6: main.UserInfo
}
var file_auth_server_proto_depIdxs = []int32{
	0, // 0: main.Auth.SignUp:input_type -> main.User
	1, // 1: main.Auth.SignIn:input_type -> main.UserCredentials
	2, // 2: main.Auth.SignInByJwt:input_type -> main.JwtToken
	0, // 3: main.Auth.UpdateUser:input_type -> main.User
	3, // 4: main.Auth.DeleteUser:input_type -> main.UserId
	3, // 5: main.Auth.GetUserInfo:input_type -> main.UserId
	4, // 6: main.Auth.SignUp:output_type -> main.Result
	4, // 7: main.Auth.SignIn:output_type -> main.Result
	4, // 8: main.Auth.SignInByJwt:output_type -> main.Result
	4, // 9: main.Auth.UpdateUser:output_type -> main.Result
	5, // 10: main.Auth.DeleteUser:output_type -> main.Successful
	6, // 11: main.Auth.GetUserInfo:output_type -> main.UserInfo
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_server_proto_init() }
func file_auth_server_proto_init() {
	if File_auth_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_server_proto_rawDesc), len(file_auth_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_server_proto_goTypes,
		DependencyIndexes: file_auth_server_proto_depIdxs,
	}.Build()
	File_auth_server_proto = out.File
	file_auth_server_proto_goTypes = nil
	file_auth_server_proto_depIdxs = nil
}
